# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: csgo
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - /mnt/storage/IFA/csgofast:/var/lib/mysql
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  csgo_mongo:
    image: mongo:3.6-jessie
    restart: always
    volumes:
      - /mnt/storage/IFA/csgofast_mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password